application: parsedsite
version: 1
runtime: python
api_version: 1

handlers:
- url: /(.*\.(gif|png|jpg|ico|js|css|ttf|ogg|mp4))
  static_files: \1
  upload: (.*\.(gif|png|jpg|ico|js|css|ttf|ogg|mp4))

- url: /robots.txt
  static_files: robots.txt
  upload: robots.txt 

- url: .*
  script: main.py
