#include <VirtualMachine/VirtualMachine.hpp>
#include <Statement/Statement.hpp>
#include <version_info.hpp>
#include <vector>
#include <iostream>
#include <sstream>
#include <map>

int PushInt(unsigned char* instructions, int current, int value) {
	instructions[current] = LoadConstOp;
	current++;
	instructions[current] = ByteInt;
	current++;
	*((int*)(instructions+current)) = value;
	current += sizeof(int);
	return current;
}

int Add(unsigned char* instructions, int current) {
	instructions[current] = AddOp;
	current++;
	return current;
}

int Subtract(unsigned char* instructions, int current) {
	instructions[current] = SubtractOp;
	current++;
	return current;
}

int Divide(unsigned char* instructions, int current) {
	instructions[current] = DivideOp;
	current++;
	return current;	
}

int Multiply(unsigned char* instructions, int current) {
	instructions[current] = MultiplyOp;
	current++;
	return current;	
}


extern int yylex();
extern void yyparse();
extern FILE* yyin;
extern std::vector<Statement*>* Statements;
extern std::map<std::string, int> Variables;

int main(int argc, char** argv) {

/**
	int c = 0;
	unsigned char* instructions = new unsigned char[4096];
	c = PushInt(instructions, c, 12);
	c = PushInt(instructions, c, 24);
	c = Add(instructions, c);
	c = PushInt(instructions, c, 9);
	c = Add(instructions, c);
	c = PushInt(instructions, c, 5);
	c = Subtract(instructions, c);
	c = PushInt(instructions, c, 2);
	c = Divide(instructions, c);
	c = PushInt(instructions, c, 5);
	c = Multiply(instructions, c);

	for (int i = 0; i < c; i++) {
		printf("%i ", instructions[i]);
	}
	printf("\n");


	SP<InstructionList> aList = new InstructionList(instructions, c);

	VirtualMachine a;
	a.setInstructions(aList);

	a.execute();
*/

	printf("Scribble %i.%i.%i\n", VERSION_MAJOR, VERSION_MINOR, VERSION_REVISION);

	// open a file handle to a particular file:
	FILE *myfile = fopen("test.scribble", "r");

	// make sure it's valid:
	if (!myfile) {
		printf("unable to open input\n");
		return -1;
	}

	// set lex to read from it instead of defaulting to STDIN:
	yyin = myfile;
	
	// lex through the input:
	yyparse();

	std::string programSource = "";
	std::vector<Statement*> stm = *Statements;
	for (int i = 0; i < Statements->size(); ++i) {

		programSource += Statements->at(i)->GenerateBytecode();

		if (i < Statements->size() - 1) {
			programSource += "\n";
		}

	}

	std::string va = "";
	std::map<std::string, int>::iterator i;
	for (i = Variables.begin(); i != Variables.end(); ++i) {
		std::stringstream j;
		j << i->first;
		j << " ";
		j << i->second;
		j << "\n";
		va += j.str();
	}

	printf("--VARIABLES--\n%s--END-VARIABLES--\n--OUTPUT GENERATED BYTECODE--\n%s\n--END GENERATED BYTECODE--\n", va.c_str(), programSource.c_str());

	printf("Exit\n");
}
