#ifndef _VERSION_INFO_DEF_H_
#define _VERSION_INFO_DEF_H_

#define PROJECT_NAME "Scribble"

#define VERSION_MAJOR 0
#define VERSION_MINOR 3
#define VERSION_BUILD_NUMBER 115

#endif //_VERSION_INFO_DEF_H_
